name: My first workflow
on: [push, workflow_dispatch]

jobs:
  my-first-job:
    runs-on: ubuntu-latest
    steps:
      - run: echo hello
      - name: run a script
        run: echo hey again
      - uses: actions/checkout@v4.1.1
      - name: Dump GitHub context
        run: echo '${{ toJSON(github) }}'
      - name: Dump job context
        run: echo '${{ toJSON(job) }}'
      - name: Dump runner context
        run: echo '${{ toJSON(runner) }}'
      - name: Dump env context
        run: echo '${{ toJSON(env) }}'
      - run: |
          echo "## :rocket: Summary" >> $GITHUB_STEP_SUMMARY
          echo "🎉 The job was triggered by event: ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "🔎 The name of your branch is ${{ github.ref }}."
